spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/gestaoGastos?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${dbPasswordDev:admin}
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          ssl:
            enable: 'false'
          auth: 'true'
    host: smtp.gmail.com
    username: digidatasistemas@gmail.com
    password: ${EMAILPASSWOR}
    test-connection: 'true'
    port: '587'

security:
  oauth2:
    client:
      client-secret: '123'
      client-id: algaworks
      scope: password
gestao:
  jwt:
    secret: gestaoGasto